---
docker_systemd_service_container_name: "nginx"
docker_systemd_service_image: nginx:1.27
docker_systemd_service_container_env:
  TEST_ENV: test
docker_systemd_service_container_pull_image: true
docker_systemd_service_container_pull_force_source: false
docker_systemd_service_flags:
  - privileged
  - network: host
  - cap-add:
      - NET_ADMIN
docker_systemd_service_container_cmd: []
docker_systemd_service_name: "{{ docker_systemd_service_container_name }}_container"
docker_systemd_service_systemd_options: []
docker_systemd_service_start: true
